bpf: fix overriding the functions for allocating executable memory
Without LTO __weak attribute doesn't work properly and causes compilation
to fail with undefined reference errors:

kernel/bpf/core.o: In function `bpf_jit_alloc_exec':
core.c:(.text+0xbc4): undefined reference to `module_alloc'
kernel/bpf/core.o: In function `bpf_jit_free_exec':
core.c:(.text+0xbd8): undefined reference to `module_memfree'

Wrap module calls in an LTO and MODULES ifdefs to avoid this for good.

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>